<?php

/**
 * @file
 * The main module file.
 *
 * Provides input filter hooks
 */

/*
 * Implements hook_filter_info.
 */
function winerlinks_filter_info() {
  $filters['winerlinks'] = array(
    'title' => t('WinerLinks'),
    'description' => t('Creates permalinks for on paragraphs.'),
    'process callback' => 'winerlinks_filter',
    'cache' => FALSE,
  );
  return $filters;
}

/**
 * Filter callback
 */
function winerlinks_filter( $content ) {

  preg_match_all("/\<p\>(.*?)\<\/p\>/is", $content, $paragraphs);

  $output = array();

  if ( !empty( $paragraphs[1] ) ) {
    $symbol = variable_get('winerlinks_permalink_symbol', '&para;');
    $position = variable_get('winerlinks_permalink_position', 'start');

    foreach ( $paragraphs[1] as $key => $content ) {
      $id = 'para-' . ($key+1);
      $link = l( $symbol, 'node/' . arg(1), array('fragment' => $id, 'html' => TRUE, array('attributes' => array('class' => 'winerlink'))) );
      $p = '<p id="' . $id . '">';

      if ( $position == 'start' ) {
        $output[] = $p . $link . $content . '</p>';
      }
      else{
        $output[] = $p . $content . $link . '</p>';
      }
    }
  }

  return implode('', $output);

}
